name = "oauth-validator"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".output/public"

# Environment variables that need to be available at runtime on the Worker.
# Add secrets via: wrangler pages secret put <NAME>
# [vars]
# EXAMPLE_VAR = "value"
