// app/router.tsx
// ---------------------------------------------------------------------------
// TanStack Start router factory.
//
// routeTree.gen.ts is auto-generated by vinxi on first `npm run dev`.
// Until that file exists, TypeScript will report a missing module — run the
// dev server once and the error will resolve.
//
// defaultSsr: false  → React components render entirely client-side.
//                      The Worker only serves the HTML shell and API routes.
// ---------------------------------------------------------------------------

import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

export function createAppRouter() {
  return createRouter({
    routeTree,
    defaultPreload: 'intent',
    scrollRestoration: true,
    defaultSsr: false,
  })
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof createAppRouter>
  }
}
